baseurl= "http://fanzy.me"
languageCode= "en-us"
title= "fz84"
theme= "hyde"

[params]
	Description= "System & security"
	author= "Fan Zhang"
	motto= "Less is more"
	Index = "True"
    disqusShortname = "FZ84"

[[menu.main]]
	name = "Blogs"
	url = "/post/"

[taxonomies]
	tag = "tags"
	category = "categories"


